repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files

- repo: https://github.com/psf/black
  rev: 22.12.0
  hooks:
  - id: black
    args: [--config, pyproject.toml]
    files: \.py$

- repo: https://github.com/charliermarsh/ruff-pre-commit
  # Ruff version.
  rev: 'v0.0.241'
  hooks:
    - id: ruff

- repo: https://github.com/jazzband/pip-tools
  rev: 6.12.0
  hooks:
  - id: pip-compile
    name: pip-compile requirements.in
    stages: [push]
    args: [--resolver=backtracking, requirements/requirements.in]
    files: ^requirements/requirements\.(in|txt)$
  - id: pip-compile
    name: pip-compile requirements-dev.in
    stages: [push]
    args: [--resolver=backtracking, requirements/requirements-dev.in]
    files: ^requirements/requirements-dev\.(in|txt)$
