repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files

- repo: https://github.com/psf/black
  rev: 22.12.0
  hooks:
  - id: black
    args: [--config, pyproject.toml]
    files: \.py$

- repo: https://github.com/pycqa/isort
  rev: 5.11.3
  hooks:
  - id: isort
    args: [--settings-path, pyproject.toml]
    files: \.py$

- repo: https://github.com/pycqa/autoflake
  rev: v2.0.0
  hooks:
  - id: autoflake
    name: Remove unused variables and imports
    language: python
    args: ["--in-place", "--remove-all-unused-imports", "--remove-unused-variables", "--expand-star-imports", "--ignore-init-module-imports"]
    files: \.py$

- repo: https://github.com/jazzband/pip-tools
  rev: 6.12.0
  hooks:
  - id: pip-compile
    name: pip-compile requirements.in
    args: [--resolver=backtracking, requirements/requirements.in]
    files: ^requirements/requirements\.(in|txt)$
  - id: pip-compile
    name: pip-compile requirements-dev.in
    args: [--resolver=backtracking, requirements/requirements-dev.in]
    files: ^requirements/requirements-dev\.(in|txt)$
  - id: pip-compile
    name: pip-compile requirements-serving.in
    args: [--resolver=backtracking, --upgrade, requirements/requirements-serving.in]
    files: ^requirements/requirements-serving\.(in|txt)$
