name: pre-commit checks
on:
  push:
  pull_request:
    branches:
      - dev
  workflow_dispatch:
    branches:
      - dev
      - main

jobs:
  pre-commit-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '2'
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: Pre-Commit Checks
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
          echo "Running pre-commit scans:"
          pre-commit run -v --files $(git --no-pager  diff --name-only HEAD^ -- HEAD)
        shell: bash
