name: Upload Python Package

on: [push]

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python3 -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install tox==4.0.16
        tox
    - name: Fetch data
      run: |
        source venv/bin/activate
        tox -e fetch_data
      env:
        KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
        KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
    - name: Train model
      run: |
        source venv/bin/activate
        tox -e train_model
    - name: Publish model
      run: |
        source venv/bin/activate
        tox -e publish_model
      env:
        GEMFURY_PUSH_URL: ${{ secrets.GEMFURY_PUSH_URL }}